### ISSUE TITLE
Query about LEDs

### ISSUE THREAD

**Issue by DLopezGo90** [solartempest/keyboards_sofleV2.1RGB#1] opened 2021-09-02 20:59 UTC
Hi friend, I have this same keyboard (Sofle RGB Keyhive v2.1) and for the firmware I use the one that Keyhive shared

But I'm having some issue with LEDs flickering and I'm suspecting it's a firmware issue because I have already desoldered and soldered new LEDs

Have you had this LED flickering? Maybe your firmware could fix it?

**Comment by solartempest** [comment] 2021-09-02 22:10
Some people have reported that they had LED issues with the keyhive firmware but personally I was okay. Definitely worth a shot flashing my firmware to know for sure. It's a quick test and you might like some of the features.

Make sure to save your VIA layout before flashing, if you haven't already. After flashing my firmware, you will need to import my sofle VIA keymap.json keymap and then load the sofle VIA layout.json for the mappings (not sure how familiar you are with this).

I have had LED flickering when building and on another keyboard. Normally that means a bad solder connection or failed LED. That is most often caused by overheating when soldering. Do you have spare LEDs?

**Comment by DLopezGo90** [comment] 2021-09-02 23:24
So you didn't have LEDs issues even using the keyhive firmware

Yes, I have spare LEDs. Should I desolder the old ones and solder new ones? Any advice when soldering LEDs? Do you use 63/37? What station temperature? A special technique when soldering LEDs? 

Thanks in advance

**Comment by solartempest** [comment] 2021-09-02 23:49
Nope, no issues with the LEDs even with the keyhive firmware.

I have had LEDs go bad on another keyboard with flickering, replaced them, and the issue went away.

As for technique, some people recommend a temp as low as 220C but I found it was a struggle eve with 63/37, I ended up soldering at 300C (280C may be safer). If you go higher than 300C you will likely burn it out. I forgot to change my temp once and burnt an LED easily at 330C.

You should remove the first LED in the chain that is giving you trouble. Likely that is the problem or else the one right upstream of that. Make sure you have enough spare LEDs to replace any that you remove... it is tricky. The small little LEDs for keys are much easier to add/remove than the big ones for the underglow.

I like to use a knife tip (k type) which lets me melt both pads at the same time. If you do not have that then alternate between both pads on one side. I add extra solder on both sides to increase the mass for more working time - you can have a blob that connects both pads. Then I melt that side briefly and VERY gently lift the LED on that side with tweezers and keep swapping between both sides. The goal is to not get too hot to burn the LED nor rip the pad on the PCB. You want to lift little-by-little like a see saw until eventually you can get it high enough to take off. Since you have extra LEDs and they are cheap, it is better to be safe by burning a LED when you remove it than lifting a pad on the PCB.

After you remove the LED, you can use a solder sucker to suck off the extra solder and iron to make it smooth/flat on the PCB. Then you can use a small piece of wire to jumper the Din to Dout pins, bypassing that location to see if you removed the problem. Work methodically, one at a time, because removing is challenging and you may risk burning out good LEDs. It is better to remove and test to find the problem instead of touching everything.

To put them back, I like to have one pad tinned, melt it and tack one big LED corner there, align it, then do the others. For the small LEDs in the holes, I just fluxed both sides and drag-soldered both pads at the same time. Hopefully that is clear and helps?

**Comment by DLopezGo90** [comment] 2021-09-03 07:48
Yea, I will desolder and resolder taking into account your advide. By the way, when you used the keyhive firmware you used different RGB effects (plain, breathing, rainbow mood, rainbow swirl, etc)?

**Comment by solartempest** [comment] 2021-09-03 15:13
Yes, with the keyhive firmware there were all the RGB effects. On my firmware, I have only enabled the static gradient because that was my favourite/preference and to save on firmware space.

If you remove the slave side logo on the OLED, you should have enough firmware space to add a couple RGB light effects back in. Or if use the stock LED code or Luna.

**Comment by solartempest** [comment] 2021-09-11 20:10
Closing this issue as the firmware is functional. For the latest changes or further issues feel free to open on my main fork, where this firmware will now be maintained. Thanks!

**Closed as completed by solartempest** 2021-09-11 20:10 UTC
